gcc: sudoku_solver_a.c sudoku_solver_b.c sudoku_solver_c.c
	gcc -o sudoku_solver_a sudoku_solver_a.c -fopenmp -lm
	gcc -o sudoku_solver_b sudoku_solver_b.c -fopenmp -lm
	gcc -o sudoku_solver_c sudoku_solver_c.c -fopenmp -lm

clean:
	rm -f sudoku_solver_a sudoku_solver_b sudoku_solver_c
